### ISSUE TITLE
NullPointerException - ChatBoxId

### ISSUE THREAD

**Issue by umdkevin** [muchino/confluence.chat#121]
Oliver, I get the null pointer below when I try to delete chat history for a user that no longer exists.

Cause
java.lang.NullPointerException
    at confluence.chat.model.ChatBoxId.<init>(ChatBoxId.java:42)
Stack Trace:[hide]
java.lang.NullPointerException
	at confluence.chat.model.ChatBoxId.<init>(ChatBoxId.java:42)
	at confluence.chat.actions.GetUserHistoryAction.deleteBox(GetUserHistoryAction.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
![screen shot 2016-04-26 at 7 47 54 am](https://cloud.githubusercontent.com/assets/12801070/14817225/cf6e1414-0b83-11e6-9bce-fc081b49ed1e.png)

**Comment by muchino** [comment]
I will have a Look into this issue and will fix it
Am 26.04.2016 13:52 schrieb "umdkevin" <notifications@github.com>:
